DELIMITER $$

CREATE PROCEDURE getLatestPerformerAutoIncrementId()
BEGIN
	SELECT `AUTO_INCREMENT`
FROM  INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'band_finder'
AND   TABLE_NAME   = 'performer';
END$$

DELIMITER ;