SELECT userId, eventId, date
FROM (SELECT userId, eventId, date
	FROM musician
	NATURAL JOIN PERFORMER
	NATURAL JOIN PERFORM
	NATURAL JOIN EVENT
	WHERE NOW() < date
	UNION
	SELECT userId, eventId, date
	FROM musician
	NATURAL JOIN joint
	NATURAL JOIN band
	NATURAL JOIN PERFORMER
	NATURAL JOIN PERFORM
	NATURAL JOIN EVENT
	WHERE NOW() < date
	GROUP BY userId)
